const Courses = [
    {
        Id: "1",
        Name: "Diploma in Interior Architecture Designing",
        ShortName: "DIAD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Autocad, Photoshop",
        Jobopportunities: "Interior decorator, Free lancing",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Scaling Methods",
            "Design fundamentals",
            "Building materials",
            "Building Components",
            "Anthropometrics",
            "Colours in Interior Design",
            "History of Architecture",
            "Furniture Sketching(Residential)",
            "History of Furniture",
            "Wall Décor’ Techniques",
            "Services Basic",
            "Bathroom Project",
            "Residential Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: "2",
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 23400,
        BasicFee: 130000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 153400,
        FeeInstallments: 9,
        FeeInstallment: [30000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: "3",
        Name: "Diploma in Furniture Designing",
        ShortName: "DIFD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "AUTOCAD, PHOTOSHOP,3DS MAX",
        CourseContent: [
            "Introduction to concept of Furniture Decoration",
            "History of furniture",
            "Furniture sketching residential and commercial",
            "Techniques of Furniture Designing",
            "Furniture style according different areas",
            "Colour schemes",
            "Design Trends",
            "Types of wood",
            "New Construction",
            "Freehand Drawing",
            "Remoulding",
            "Carpentry and joinery",
            "Materials",
            "Hardware & Fittings",
            "Different finishes of furniture",
            "Estimation and costing",
            "Low cost furniture",
            "Customize furniture",
            "Modular furniture",
            "Theme based furniture",
            "Stone furniture"],
        GST: 23400,
        BasicFee: 130000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 153400,
        FeeInstallments: 9,
        FeeInstallment: [30000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: "4",
        Name: "Professional Diploma in Interior Architecture Designing",
        ShortName: "PDIAD",
        Duration: "2 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Designing",
            "Freehand Drawing",
            "Scaling Methods",
            "Design fundamentals",
            "Building materials",
            "Building Components",
            "Colours in Interior Design",
            "Anthropometrics",
            "History of Architecture",
            "History of Furniture",
            "Furniture Sketching (Residential)",
            "Furniture Sketching (commercial)",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Services (all)",
            "Residential Space Planning",
            "Bathroom Project",
            "Residential Project",
            "Commercial space planning",
            "Mood board",
            "Wall Treatments",
            "Vastu basic",
            "Design decision process",
            "Execution process",
            "Landscaping",
            "Estimation",
            "Commercial project(2)",
            "Model making",
            "etc"],
        BasicFee: 300000,
        GST: 54000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 354000,
        FeeInstallments: 18,
        FeeInstallment: [50000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 15000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: "5",
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: "6",
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 7,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 8,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 9,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 10,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 11,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 12,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 13,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 14,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 15,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 16,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 17,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 18,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    },
    {
        Id: 19,
        Name: "Diploma in interior Decoration and Designing",
        ShortName: "DIDD",
        Duration: "1 Year",
        ClassDuraction: 2,
        ClassesinWeek: 5,
        ClassesinMonth: 20,
        TotalClasses: 240,
        SoftwaresUsed: "Google Sketchup, Photoshop",
        CourseContent: [
            "Introduction to concept of Interior Decoration",
            "Freehand Drawing",
            "Colours in Interior Design",
            "Furniture Sketching(Residential)",
            "Furniture Sketching(commercial)",
            "Role of accessories",
            "Wall Décor’ Techniques",
            "Fabric and furnishing",
            "Mood boards",
            "Project"],
        GST: 27000,
        BasicFee: 150000,
        RegistrationFee: 20000,
        TotalFeeWithGST: 177000,
        FeeInstallments: 10,
        FeeInstallment: [40000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000, 10000]
    }
];

export default Courses;